# Generated by Django 6.0 on 2025-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_date', models.DateTimeField()),
                ('traffic_control_device', models.CharField(blank=True, max_length=60)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('lighting_condition', models.CharField(blank=True, max_length=50)),
                ('first_crash_type', models.CharField(blank=True, max_length=60)),
                ('trafficway_type', models.CharField(blank=True, max_length=60)),
                ('alignment', models.CharField(blank=True, max_length=60)),
                ('roadway_surface_cond', models.CharField(blank=True, max_length=60)),
                ('road_defect', models.CharField(blank=True, max_length=60)),
                ('crash_type', models.CharField(blank=True, max_length=60)),
                ('intersection_related', models.BooleanField(default=False)),
                ('damage', models.CharField(blank=True, max_length=60)),
                ('prim_contributory_cause', models.CharField(blank=True, max_length=120)),
                ('num_units', models.IntegerField()),
                ('most_severe_injury', models.CharField(blank=True, max_length=60)),
                ('injuries_total', models.IntegerField()),
                ('injuries_fatal', models.IntegerField()),
                ('injuries_incapacitating', models.IntegerField()),
                ('injuries_non_incapacitating', models.IntegerField()),
                ('injuries_reported_not_evident', models.IntegerField()),
                ('injuries_no_indication', models.IntegerField()),
                ('crash_hour', models.IntegerField()),
                ('crash_day_of_week', models.IntegerField()),
                ('crash_month', models.IntegerField()),
            ],
        ),
    ]
